### ISSUE TITLE
PR 2

### ISSUE THREAD

**Issue by marota** [powsybl/pypowsybl-grid2opbackend#11]
Une PR a venir avec données et code fonctionnel sur cas RTE + CI/CD + packaging python

- [x] Data RTE qui converge (cf issue https://github.com/powsybl/pypowsybl-grid2opbackend/issues/2)
- [x] Code qui tourne en un temps raisonable
- [x] CI/CD (cf issue avec github actions) (cf issue https://github.com/powsybl/pypowsybl-grid2opbackend/issues/6)
- [x] package python sur Pypi (cf issue https://github.com/powsybl/pypowsybl-grid2opbackend/issues/9)
- [x] additional test suite now available cf issue https://github.com/powsybl/pypowsybl-grid2opbackend/issues/14)

**Comment by tschuppr** [comment]
I made some code profilling and found the improvments to have a reasonnable time for our backend to run the chronics (approx 1.3 it/s). It will already be in PR1 with other improvments asked by Benjamin.

**Comment by marota** [comment]
@tschuppr J'ai rajouté un item pour compléter l'aspect test CI/CD suite au dernier dev de Benjamin sur la test suite à réaliser pour le backend. Dans la continuité des tests déjà réutilisés

**Comment by marota** [comment]
Mentionner dans le ReadMe ce qui est disponible sur la AIOD platform, le dataset en particulier

**Comment by tschuppr** [comment]
The pull request can be found [here](https://github.com/powsybl/pypowsybl-grid2opbackend/pull/19)

**Comment by marota** [comment]
Completed
